---
- name: Install Helm on Master node
  hosts: master
  become: true
  tasks:
    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm.sh
        mode: '0755'

    - name: Install Helm
      command: /tmp/get-helm.sh
      args:
        creates: /usr/local/bin/helm

    - name: Verify Helm installation
      command: helm version
      register: helm_version

    - name: Display Helm version
      debug:
        msg: "Helm installed successfully: {{ helm_version.stdout }}"