---
# ------------------------------------------------------------
# MASTER PLAY
# ------------------------------------------------------------
- name: Install k3s on Master node
  hosts: master
  become: true
  tasks:

    - name: Install k3s control plane
      shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_EXEC="server --disable traefik --cluster-init --node-taint 'node-role.kubernetes.io/master=true:NoSchedule'" \
        K3S_KUBECONFIG_MODE="644" \
        sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s to be ready
      command: /usr/local/bin/k3s kubectl get nodes
      register: k3s_ready
      until: k3s_ready.rc == 0
      retries: 20
      delay: 10

    - name: Retrieve k3s node token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_encoded

    - name: Set k3s node token fact
      set_fact:
        k3s_node_token: "{{ k3s_token_encoded.content | b64decode | trim }}"

# ------------------------------------------------------------
# WORKER PLAY
# ------------------------------------------------------------
- name: Install k3s on worker nodes
  hosts: worker-node
  become: true
  vars:
    master_ip: "{{ groups['master'][0] }}"
    join_token: "{{ hostvars[groups['master'][0]]['k3s_node_token'] | default('') }}"
  tasks:

    - name: Install k3s agent
      shell: |
        curl -sfL https://get.k3s.io | \
        K3S_URL="https://{{ master_ip }}:6443" \
        K3S_TOKEN="{{ join_token }}" \
        sh -
      args:
        creates: /usr/local/bin/k3s
