---
- name: Prepare master node
  hosts: master
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Upgrade apt packages
      apt:
        upgrade: dist

    - name: Install prerequisites for k3s
      apt:
        name:
          - curl
          - wget
          - ca-certificates
          - iptables
          - net-tools
          - lsb-release
          - nfs-common
        state: present
        update_cache: yes

- name: Prepare worker nodes
  hosts: worker-node
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Upgrade apt packages
      apt:
        upgrade: dist

    - name: Install prerequisites for k3s
      apt:
        name:
          - curl
          - wget
          - ca-certificates
          - iptables
          - net-tools
          - lsb-release
          - nfs-common
        state: present
        update_cache: yes
